import type { Challenge } from './types';

// I know i could take the index but since I may be skipping days at some point I add it manually
export const challenges: Challenge[] = [
	{ day: 1, name: 'Naughty or nice', rating: 0.8 },
	{ day: 2, name: 'Hungry Santa', rating: 0.95 },
	{ day: 3, name: 'Sled Load Balancer', rating: 0.95 },
	{ day: 4, name: 'Heart rate monitor', rating: 1 },
	{ day: 5, name: '?', rating: 0 },
	{ day: 6, name: '?', rating: 0 },
	{ day: 7, name: '?', rating: 0 },
	{ day: 8, name: '?', rating: 0 },
	{ day: 9, name: '?', rating: 0 },
	{ day: 10, name: '?', rating: 0 },
	{ day: 11, name: '?', rating: 0 },
	{ day: 12, name: '?', rating: 0 },
	{ day: 13, name: '?', rating: 0 },
	{ day: 14, name: '?', rating: 0 },
	{ day: 15, name: '?', rating: 0 },
	{ day: 16, name: '?', rating: 0 },
	{ day: 17, name: '?', rating: 0 },
	{ day: 18, name: '?', rating: 0 },
	{ day: 19, name: '?', rating: 0 },
	{ day: 20, name: '?', rating: 0 },
	{ day: 21, name: '?', rating: 0 },
	{ day: 22, name: '?', rating: 0 },
	{ day: 23, name: '?', rating: 0 },
	{ day: 24, name: '?', rating: 0 },
	{ day: 25, name: '?', rating: 0 },
	{ day: 26, name: '?', rating: 0 },
	{ day: 27, name: '?', rating: 0 },
	{ day: 28, name: '?', rating: 0 },
	{ day: 29, name: '?', rating: 0 },
	{ day: 30, name: '?', rating: 0 },
	{ day: 31, name: '?', rating: 0 }
] as const;
